"""add created_at indexes

Revision ID: 0bb14b80309f
Revises: d523ab0e5a3b
Create Date: 2026-09-02 18:10:23.014530

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0bb14b80309f"
down_revision: str | None = "d523ab0e5a3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_analyses_created_at"), "analyses", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_interview_messages_created_at"),
        "interview_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_sessions_created_at"),
        "interview_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resumes_created_at"), "resumes", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_index(op.f("ix_resumes_created_at"), table_name="resumes")
    op.drop_index(
        op.f("ix_interview_sessions_created_at"), table_name="interview_sessions"
    )
    op.drop_index(
        op.f("ix_interview_messages_created_at"), table_name="interview_messages"
    )
    op.drop_index(op.f("ix_analyses_created_at"), table_name="analyses")
    # ### end Alembic commands ###
