"""add position_type to interview_sessions

Revision ID: ccad45b9a0e0
Revises: 0bb14b80309f
Create Date: 2026-09-02 19:13:20.943261

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccad45b9a0e0"
down_revision: str | None = "0bb14b80309f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interview_sessions",
        sa.Column("position_type", sa.String(length=20), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interview_sessions", "position_type")
    # ### end Alembic commands ###
